name: build container

on:
  push:
    tags:
      - "*-*"

  pull_request:
    branches: [main, master]

env:
  REGISTRY: docker.io

jobs:
  build-recursor:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref_name, 'rec-') }}
    env:
      AUTHOR: olofvndrhr
      IMAGE: pdns-recursor
      CONTEXT: recursor
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup qemu
        uses: docker/setup-qemu-action@v2

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: get container metadata
        uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ${{ env.REGISTRY }}/${{ env.AUTHOR }}/${{ env.IMAGE }}
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: login to docker.io container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}

      - name: login to private container registry
        uses: docker/login-action@v2
        with:
          registry: git.44net.ch
          username: ${{ secrets.CR_PRIV_USERNAME }}
          password: ${{ secrets.CR_PRIV_PASSWORD }}

      - name: build and push docker image @amd64+arm64
        uses: docker/build-push-action@v4
        with:
          push: ${{ gitea.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          context: ${{ env.CONTEXT }}
          file: ${{ env.CONTEXT }}/Dockerfile
          provenance: false
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

  build-auth:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref_name, 'auth-') }}
    env:
      AUTHOR: olofvndrhr
      IMAGE: pdns-auth
      CONTEXT: auth
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup qemu
        uses: docker/setup-qemu-action@v2

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: get container metadata
        uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ${{ env.REGISTRY }}/${{ env.AUTHOR }}/${{ env.IMAGE }}
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: login to docker.io container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}

      - name: login to private container registry
        uses: docker/login-action@v2
        with:
          registry: git.44net.ch
          username: ${{ secrets.CR_PRIV_USERNAME }}
          password: ${{ secrets.CR_PRIV_PASSWORD }}

      - name: build and push docker image @amd64+arm64
        uses: docker/build-push-action@v4
        with:
          push: ${{ gitea.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          context: ${{ env.CONTEXT }}
          file: ${{ env.CONTEXT }}/Dockerfile
          provenance: false
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

  build-lightningstream:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref_name, 'ls-') }}
    env:
      AUTHOR: olofvndrhr
      IMAGE: pdns-lightningstream
      CONTEXT: lightningstream
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup qemu
        uses: docker/setup-qemu-action@v2

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: get container metadata
        uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ${{ env.REGISTRY }}/${{ env.AUTHOR }}/${{ env.IMAGE }}
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: login to docker.io container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}

      - name: login to private container registry
        uses: docker/login-action@v2
        with:
          registry: git.44net.ch
          username: ${{ secrets.CR_PRIV_USERNAME }}
          password: ${{ secrets.CR_PRIV_PASSWORD }}

      - name: build and push docker image @amd64+arm64
        uses: docker/build-push-action@v4
        with:
          push: ${{ gitea.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          context: ${{ env.CONTEXT }}
          file: ${{ env.CONTEXT }}/Dockerfile
          provenance: false
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
