name: test build container

on:
  pull_request:
    branches: [main, master]

jobs:
  test-build-recursor:
    uses: actions/workflows/.gitea/workflows/build_container.yml@master
    with:
      registry: docker.io
      image-name: olofvndrhr/pdns-recursor
      context: recursor
      dockerfile: recursor/Dockerfile
      platforms: linux/amd64
    secrets:
      cr-username: ${{ secrets.CR_USERNAME }}
      cr-password: ${{ secrets.CR_PASSWORD }}

  test-build-auth:
    uses: actions/workflows/.gitea/workflows/build_container.yml@master
    with:
      registry: docker.io
      image-name: olofvndrhr/pdns-auth
      context: auth
      dockerfile: auth/Dockerfile
      platforms: linux/amd64
    secrets:
      cr-username: ${{ secrets.CR_USERNAME }}
      cr-password: ${{ secrets.CR_PASSWORD }}

  test-build-lightningstream:
    uses: actions/workflows/.gitea/workflows/build_container.yml@master
    with:
      registry: docker.io
      image-name: olofvndrhr/pdns-lightningstream
      context: lightningstream
      dockerfile: lightningstream/Dockerfile
      platforms: linux/amd64
    secrets:
      cr-username: ${{ secrets.CR_USERNAME }}
      cr-password: ${{ secrets.CR_PASSWORD }}
