name: test build container

on:
  pull_request:
    branches: [main, master]

jobs:
  build-recursor:
    runs-on: ubuntu-latest
    env:
      AUTHOR: olofvndrhr
      IMAGE: pdns-recursor
      CONTEXT: recursor
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup qemu
        uses: docker/setup-qemu-action@v3

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to private container registry
        uses: docker/login-action@v3
        with:
          registry: git.44net.ch
          username: ${{ secrets.CR_PRIV_USERNAME }}
          password: ${{ secrets.CR_PRIV_PASSWORD }}

      - name: build docker image @amd64+arm64
        uses: docker/build-push-action@v6
        with:
          push: false
          platforms: linux/amd64,linux/arm64
          context: ${{ env.CONTEXT }}
          file: ${{ env.CONTEXT }}/Dockerfile
          provenance: false
          tags: "pdns-recursor:test"

  build-auth:
    runs-on: ubuntu-latest
    env:
      AUTHOR: olofvndrhr
      IMAGE: pdns-auth
      CONTEXT: auth
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup qemu
        uses: docker/setup-qemu-action@v3

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to private container registry
        uses: docker/login-action@v3
        with:
          registry: git.44net.ch
          username: ${{ secrets.CR_PRIV_USERNAME }}
          password: ${{ secrets.CR_PRIV_PASSWORD }}

      - name: build docker image @amd64+arm64
        uses: docker/build-push-action@v6
        with:
          push: false
          platforms: linux/amd64,linux/arm64
          context: ${{ env.CONTEXT }}
          file: ${{ env.CONTEXT }}/Dockerfile
          provenance: false
          tags: "pdns-auth:test"

  build-lightningstream:
    runs-on: ubuntu-latest
    env:
      AUTHOR: olofvndrhr
      IMAGE: pdns-lightningstream
      CONTEXT: lightningstream
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup qemu
        uses: docker/setup-qemu-action@v3

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to private container registry
        uses: docker/login-action@v3
        with:
          registry: git.44net.ch
          username: ${{ secrets.CR_PRIV_USERNAME }}
          password: ${{ secrets.CR_PRIV_PASSWORD }}

      - name: build docker image @amd64+arm64
        uses: docker/build-push-action@v6
        with:
          push: false
          platforms: linux/amd64,linux/arm64
          context: ${{ env.CONTEXT }}
          file: ${{ env.CONTEXT }}/Dockerfile
          provenance: false
          tags: "pdns-lightningstream:test"
