name: build container

on:
  push:
    tags:
      - "*-*"

env:
  REGISTRY: docker.io
  AUTHOR: olofvndrhr

jobs:
  build-container:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["auth", "recursor", "lightningstream", "dnsdist"]
    env:
      IMAGE: pdns-${{ matrix.target }}
      CONTEXT: ${{ matrix.target }}
    steps:
      - name: fix release tag
        if: ${{ startsWith(github.ref_name, matrix.target) }}
        run: echo "VERSION=${GITHUB_REF_NAME#*-}" >> ${GITHUB_ENV}

      - name: checkout code
        if: ${{ startsWith(github.ref_name, matrix.target) }}
        uses: actions/checkout@v4

      - name: setup qemu
        if: ${{ startsWith(github.ref_name, matrix.target) }}
        uses: docker/setup-qemu-action@v3

      - name: setup docker buildx
        if: ${{ startsWith(github.ref_name, matrix.target) }}
        uses: docker/setup-buildx-action@v3

      - name: get container metadata
        if: ${{ startsWith(github.ref_name, matrix.target) }}
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ${{ env.REGISTRY }}/${{ env.AUTHOR }}/${{ env.IMAGE }}
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},value=${{ env.VERSION }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.VERSION }}
            type=semver,pattern={{major}},value=${{ env.VERSION }}

      - name: login to docker.io container registry
        if: ${{ startsWith(github.ref_name, matrix.target) }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}

      - name: login to private container registry
        if: ${{ startsWith(github.ref_name, matrix.target) }}
        uses: docker/login-action@v3
        with:
          registry: git.44net.ch
          username: ${{ secrets.CR_PRIV_USERNAME }}
          password: ${{ secrets.CR_PRIV_PASSWORD }}

      - name: build and push docker image @amd64+arm64
        if: ${{ startsWith(github.ref_name, matrix.target) }}
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          context: ${{ env.CONTEXT }}
          file: ${{ env.CONTEXT }}/Dockerfile
          provenance: false
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: update dockerhub repo description
        if: ${{ startsWith(github.ref_name, matrix.target) }}
        uses: peter-evans/dockerhub-description@v4
        with:
          repository: ${{ env.AUTHOR }}/${{ env.IMAGE }}
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}
